apiVersion: v1
kind: Pod
metadata:
  name: clarus-db
  labels:
    tier: db
spec:
  containers:
  - name: clarus-db
    image: clarusway/clarusdb
    imagePullPolicy: IfNotPresent
    resources:
  nodeName: kube-master # with nodeName our db pod will be created on the kube-master node
  restartPolicy: Always
    
    