apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:                        # credential lari bu sekilde environmental variable olarak göndermek güvenilir degil. Cünkü bu file lari github vb yerlerde paylasiyoruz.
      - name: SECRET_USERNAME
        value: admin
      - name: SECRET_PASSWORD
        value: 1f2d1e2e67df
    resources:
    {}
  restartPolicy: Never