apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=          # this value comes from command: echo -n 'username' | base64
  password: MWYyZDFlMmU2N2Rm  # this value comes from command: echo -n 'password' | base64