apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:   # there is taint on worker node. Because of that our pods will be created on the node/nodes without taints
      - name: nginx
        image: nginx
        resources:          
        ports:
        - containerPort: 80
      tolerations:
        - key: clarus   # our taints key-value is clarus:way
          value: way    # When we use Exists attribute, we do not need to declare value. Because this attributes look for whether key exists in the file or not. If exists, our pod will be created on this node.
          effect: NoSchedule
          operator: Equal   # look for equality of clarus:way taint and NoSchedule attributes.
