apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mongo
    app: todoapp
spec:
  selector:
    name: mongo
  type: ClusterIP # It is internal. So I can only access this service within the cluster
  ports:
    - name: db
      port: 27017
      targetPort: 27017